Raditya Aji Sasmoyo (2010631170111) Algoritma K-Nearest Neighbor

Algoritma Decisions Tree

Algoritma Random Forest

Nanda Sukarno Wijaya (2010631170154) Algoritma Naive Bayes




Kang, kami dua orang di satu keleompok tapi tugas membuat 4 algoritma diselesaikan.

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/raditya2010631170111/df_20111/main/heart.csv")
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [ ]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [ ]:
!pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
df['Sex'].value_counts()

M    725
F    193
Name: Sex, dtype: int64

In [ ]:
df['Sex'].unique()

array(['M', 'F'], dtype=object)

In [ ]:
print(len(df['Sex'].unique()))
print(len(df['ChestPainType'].unique()))
print(len(df['RestingECG'].unique()))
print(len(df['ExerciseAngina'].unique()))
print(len(df['ST_Slope'].unique()))

2
4
3
2
3


Encoding kolom2 kategorikal

In [ ]:
from category_encoders import TargetEncoder
encoder_1 = TargetEncoder()
df['ChestPainType'] = encoder_1.fit_transform(df['ChestPainType'], df['HeartDisease'])
encoder_2 = TargetEncoder()
df['Sex'] = encoder_2.fit_transform(df['Sex'], df['HeartDisease'])
encoder_3 = TargetEncoder()
df['RestingECG'] = encoder_3.fit_transform(df['RestingECG'], df['HeartDisease'])
encoder_4 = TargetEncoder()
df['ExerciseAngina'] = encoder_4.fit_transform(df['ExerciseAngina'], df['HeartDisease'])
encoder_5 = TargetEncoder()
df['ST_Slope'] = encoder_5.fit_transform(df['ST_Slope'], df['HeartDisease'])
df.head()

/usr/local/lib/python3.7/dist-packages/category_encoders/target_encoder.py:124: FutureWarning: Default parameter min_samples_leaf will change in version 2.6.See https://github.com/scikit-learn-contrib/category_encoders/issues/327
  category=FutureWarning)
/usr/local/lib/python3.7/dist-packages/category_encoders/target_encoder.py:129: FutureWarning: Default parameter smoothing will change in version 2.6.See https://github.com/scikit-learn-contrib/category_encoders/issues/327
  category=FutureWarning)


Age       Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  \
0   40  0.631724       0.138728        140          289          0   
1   49  0.259067       0.354680        160          180          0   
2   37  0.631724       0.138728        130          283          0   
3   48  0.259067       0.790323        138          214          0   
4   54  0.631724       0.354680        150          195          0   

   RestingECG  MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    0.516304    172        0.351005      0.0  0.197468             0  
1    0.516304    156        0.351005      1.0  0.828261             1  
2    0.657303     98        0.351005      0.0  0.197468             0  
3    0.516304    108        0.851752      1.5  0.828261             1  
4    0.516304    122        0.351005      0.0  0.197468             0

Normalization

In [ ]:
from sklearn.preprocessing import MinMaxScaler
exclude = ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope', 'HeartDisease']
for i in df.columns:
  if i not in exclude:
    scaler = MinMaxScaler()
    df[i] = scaler.fit_transform(df[i].values.reshape(-1,1))
df.head()

Age       Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  \
0  0.244898  0.631724       0.138728       0.70     0.479270        0.0   
1  0.428571  0.259067       0.354680       0.80     0.298507        0.0   
2  0.183673  0.631724       0.138728       0.65     0.469320        0.0   
3  0.408163  0.259067       0.790323       0.69     0.354892        0.0   
4  0.530612  0.631724       0.354680       0.75     0.323383        0.0   

   RestingECG     MaxHR  ExerciseAngina   Oldpeak  ST_Slope  HeartDisease  
0    0.516304  0.788732        0.351005  0.295455  0.197468             0  
1    0.516304  0.676056        0.351005  0.409091  0.828261             1  
2    0.657303  0.267606        0.351005  0.295455  0.197468             0  
3    0.516304  0.338028        0.851752  0.465909  0.828261             1  
4    0.516304  0.436620        0.351005  0.295455  0.197468             0

Correlation

In [ ]:
df.corr()

Age       Sex  ChestPainType  RestingBP  Cholesterol  \
Age             1.000000  0.055750       0.205315   0.254399    -0.095282   
Sex             0.055750  1.000000       0.199117   0.005133    -0.200092   
ChestPainType   0.205315  0.199117       1.000000   0.057210    -0.143735   
RestingBP       0.254399  0.005133       0.057210   1.000000     0.100893   
Cholesterol    -0.095282 -0.200092      -0.143735   0.100893     1.000000   
FastingBS       0.198039  0.120076       0.151934   0.070193    -0.260974   
RestingECG      0.192085  0.047964       0.089656   0.111735    -0.074171   
MaxHR          -0.382045 -0.189186      -0.360129  -0.112135     0.235792   
ExerciseAngina  0.215793  0.190664       0.433632   0.155101    -0.034166   
Oldpeak         0.258612  0.105734       0.310808   0.164803     0.050148   
ST_Slope        0.254664  0.149566       0.401605   0.097330    -0.091428   
HeartDisease    0.282039  0.305445       0.540382   0.107589    -0.232741   

                FastingBS  RestingECG     MaxHR  ExerciseAngina   Oldpeak  \
Age              0.198039    0.192085 -0.382045        0.215793  0.258612   
Sex              0.120076    0.047964 -0.189186        0.190664  0.105734   
ChestPainType    0.151934    0.089656 -0.360129        0.433632  0.310808   
RestingBP        0.070193    0.111735 -0.112135        0.155101  0.164803   
Cholesterol     -0.260974   -0.074171  0.235792       -0.034166  0.050148   
FastingBS        1.000000    0.126490 -0.131438        0.060451  0.052698   
RestingECG       0.126490    1.000000 -0.117756        0.104193  0.088184   
MaxHR           -0.131438   -0.117756  1.000000       -0.370425 -0.160691   
ExerciseAngina   0.060451    0.104193 -0.370425        1.000000  0.408752   
Oldpeak          0.052698    0.088184 -0.160691        0.408752  1.000000   
ST_Slope         0.158839    0.072581 -0.383795        0.454117  0.441316   
HeartDisease     0.267291    0.109123 -0.400421        0.494282  0.403951   

                ST_Slope  HeartDisease  
Age             0.254664      0.282039  
Sex             0.149566      0.305445  
ChestPainType   0.401605      0.540382  
RestingBP       0.097330      0.107589  
Cholesterol    -0.091428     -0.232741  
FastingBS       0.158839      0.267291  
RestingECG      0.072581      0.109123  
MaxHR          -0.383795     -0.400421  
ExerciseAngina  0.454117      0.494282  
Oldpeak         0.441316      0.403951  
ST_Slope        1.000000      0.622664  
HeartDisease    0.622664      1.000000

1. Algoritma Logistic Regression

Model

In [ ]:
from sklearn.model_selection import train_test_split
y = df['HeartDisease']
X = df.drop('HeartDisease', axis=1)
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X, y, test_size=0.2)
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X, y, test_size=0.3)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_1, y_train_1)

LogisticRegression()

In [ ]:
y_pred_1 = model.predict(X_test_1)

In [ ]:
model_2 = LogisticRegression()
model_2.fit(X_train_2, y_train_2)
model_2.score(X_test_2, y_test_2)

0.855072463768116

In [ ]:
y_pred_2 = model.predict(X_test_2)

Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
confusion_matrix(y_test_1, y_pred_1)

array([[63, 19],
       [ 9, 93]])

1. Model

In [ ]:
a = classification_report(y_test_1, y_pred_1)
print(a)

              precision    recall  f1-score   support

           0       0.88      0.77      0.82        82
           1       0.83      0.91      0.87       102

    accuracy                           0.85       184
   macro avg       0.85      0.84      0.84       184
weighted avg       0.85      0.85      0.85       184



2. Model 2

In [ ]:
confusion_matrix(y_test_2, y_pred_2)

array([[104,  21],
       [ 17, 134]])

In [ ]:
a = classification_report(y_test_2, y_pred_2)
print(a)

              precision    recall  f1-score   support

           0       0.86      0.83      0.85       125
           1       0.86      0.89      0.88       151

    accuracy                           0.86       276
   macro avg       0.86      0.86      0.86       276
weighted avg       0.86      0.86      0.86       276



2. Algoritma K-Nearest Neighbors

Model & Membagi data latih-uji

In [ ]:
X_train_3, X_test_3, y_train_3, y_test_3 = train_test_split(X, y, test_size=0.20)

Standardisasi

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 
scaler.fit(X_train_3)
X_train_3 = scaler.transform(X_train_3)
X_test_3 = scaler.transform(X_test_3)

K-Nearest Neighbors

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model_3 = KNeighborsClassifier (n_neighbors=4)
model_3.fit(X_train_3, y_train_3)
y_pred_3 = model_3.predict(X_test_3)
y_pred_3

array([0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0])

In [ ]:
model_3.predict_proba(X_test_3)

array([[0.5 , 0.5 ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.25, 0.75],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.75, 0.25],
       [0.25, 0.75],
       [0.75, 0.25],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.75, 0.25],
       [0.5 , 0.5 ],
       [0.25, 0.75],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.25, 0.75],
       [0.  , 1.  ],
       [0.75, 0.25],
       [0.5 , 0.5 ],
       [0.  , 1.  ],
       [0.75, 0.25],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.25, 0.75],
       [0.5 , 0.5 ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.25, 0.75],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  ,

Confusion Matrix ke Model 3

In [ ]:
print(confusion_matrix(y_test_3, y_pred_3))

[[89  4]
 [14 77]]


In [ ]:
print(classification_report(y_test_3, y_pred_3))

              precision    recall  f1-score   support

           0       0.86      0.96      0.91        93
           1       0.95      0.85      0.90        91

    accuracy                           0.90       184
   macro avg       0.91      0.90      0.90       184
weighted avg       0.91      0.90      0.90       184



3. Decisions Tree

Model dan membagi data latih uji

In [ ]:
%matplotlib inline
from pandas import Series, DataFrame
import sklearn.metrics 
X_train_4, X_test_4, y_train_4, y_test_4 = train_test_split(X, y, test_size=.2, random_state=0)
print('X_train_4 = ', X_train_4.shape)
print('X_test_4 = ', X_test_4.shape)
print('y_train_4 = ', y_train_4.shape)
print('y_test_4 = ', y_test_4.shape)

X_train_4 =  (734, 11)
X_test_4 =  (184, 11)
y_train_4 =  (734,)
y_test_4 =  (184,)


Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model_4 = DecisionTreeClassifier()
model_4.fit(X_train_4, y_train_4)
y_pred_4=model_4.predict(X_test_4)

Confusion Matrix ke Model 4

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
confusion_array = sklearn.metrics.confusion_matrix(y_test_4, y_pred_4)
print (confusion_array)

[[64 13]
 [27 80]]


In [ ]:
print('TN = ', confusion_array[0,0] ) #TrueNegative
print('FN = ', confusion_array[1,0] ) #FalseNegative
print('TP = ', confusion_array[1,1] ) #TruePositive
print('FP = ', confusion_array[0,1] ) #FalsePositive

TN =  64
FN =  27
TP =  80
FP =  13


In [ ]:
model_4.score(X_test_4, y_test_4)

0.782608695652174

In [ ]:
a_4 = classification_report(y_test_4, y_pred_4)
print(a_4)

              precision    recall  f1-score   support

           0       0.70      0.83      0.76        77
           1       0.86      0.75      0.80       107

    accuracy                           0.78       184
   macro avg       0.78      0.79      0.78       184
weighted avg       0.79      0.78      0.78       184



4. Algoritma Random Forest

Model & Membagi data latih-uji

In [ ]:
from sklearn import datasets
X_train_8, X_test_8, y_train_8, y_test_8 = train_test_split(X, y, test_size=.4, random_state = 0 )
print('X_train_8 = ', X_train_8.shape)
print('X_test_8 = ', X_test_8.shape)
print('y_train_8 = ', y_train_8.shape)
print('y_test_8 = ', y_test_8.shape)

X_train_8 =  (550, 11)
X_test_8 =  (368, 11)
y_train_8 =  (550,)
y_test_8 =  (368,)


Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model_8 = RandomForestClassifier(n_estimators=20, random_state = 0)
model_8.fit(X_train_8, y_train_8)
y_pred_8=model_8.predict(X_test_8)

Confusion Matrix ke Model 8

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
confusion_array = sklearn.metrics.confusion_matrix(y_test_8, y_pred_8)
print (confusion_array)

[[128  28]
 [ 25 187]]


In [ ]:
print('TN = ', confusion_array[0,0] ) #TrueNegative
print('FN = ', confusion_array[1,0] ) #FalseNegative
print('TP = ', confusion_array[1,1] ) #TruePositive
print('FP = ', confusion_array[0,1] ) #FalsePositive

TN =  128
FN =  25
TP =  187
FP =  28


In [ ]:
model_8.score(X_test_8, y_test_8)

0.8559782608695652

In [ ]:
a = classification_report(y_test_8, y_pred_8)
print(a)

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       156
           1       0.87      0.88      0.88       212

    accuracy                           0.86       368
   macro avg       0.85      0.85      0.85       368
weighted avg       0.86      0.86      0.86       368



5. Algoritma Naive Bayes

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/raditya2010631170111/df_20111/main/heart.csv')
data.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
enc = LabelEncoder()

In [ ]:
data['Age'] = enc.fit_transform(data['Age'].values)
data['Sex'] = enc.fit_transform(data['Sex'].values)
data['ChestPainType'] = enc.fit_transform(data['ChestPainType'].values)
data['RestingBP'] = enc.fit_transform(data['RestingBP'].values)
data['Cholesterol'] = enc.fit_transform(data['Cholesterol'].values)
data['FastingBS'] = enc.fit_transform(data['FastingBS'].values)
data['RestingECG'] = enc.fit_transform(data['RestingECG'].values)
data['MaxHR'] = enc.fit_transform(data['MaxHR'].values)
data['ExerciseAngina'] = enc.fit_transform(data['ExerciseAngina'].values)
data['Oldpeak'] = enc.fit_transform(data['Oldpeak'].values)
data['ST_Slope'] = enc.fit_transform(data['ST_Slope'].values)
data['HeartDisease'] = enc.fit_transform(data['HeartDisease'].values)

In [ ]:
atr_data = data.drop(columns='HeartDisease')
atr_data.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   12    1              1         41          147          0           1   
1   21    0              2         55           40          0           1   
2    9    1              1         31          141          0           2   
3   20    0              0         39           72          0           1   
4   26    1              2         49           53          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  
0     98               0       10         2  
1     82               0       20         1  
2     25               0       10         2  
3     34               1       25         1  
4     48               0       10         2

In [ ]:
cls_data = data['HeartDisease']
cls_data.head(100)

0     0
1     1
2     0
3     1
4     0
     ..
95    1
96    0
97    0
98    0
99    0
Name: HeartDisease, Length: 100, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(atr_data,cls_data, test_size=0.2, random_state=5000)
nb = GaussianNB()
nb.fit(x_train, y_train)

GaussianNB()

In [ ]:
y_pred = nb.predict(x_test)
y_pred

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1])

In [ ]:
np.array(y_test)

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1])

In [ ]:
nb.predict_proba(x_test)

array([[9.97420962e-01, 2.57903789e-03],
       [9.99725797e-01, 2.74202985e-04],
       [9.99996934e-01, 3.06607843e-06],
       [9.99899086e-01, 1.00914468e-04],
       [2.22917377e-02, 9.77708262e-01],
       [9.99691108e-01, 3.08891585e-04],
       [1.24792777e-04, 9.99875207e-01],
       [2.01559756e-01, 7.98440244e-01],
       [9.99909118e-01, 9.08824408e-05],
       [9.94869559e-01, 5.13044149e-03],
       [1.99811449e-04, 9.99800189e-01],
       [1.76116205e-04, 9.99823884e-01],
       [4.45633229e-03, 9.95543668e-01],
       [1.07825841e-02, 9.89217416e-01],
       [5.62841867e-01, 4.37158133e-01],
       [6.71503511e-01, 3.28496489e-01],
       [9.99162153e-01, 8.37846881e-04],
       [1.72285405e-03, 9.98277146e-01],
       [1.83228552e-01, 8.16771448e-01],
       [9.87648462e-01, 1.23515384e-02],
       [2.26197595e-03, 9.97738024e-01],
       [9.99103752e-01, 8.96248259e-04],
       [4.94770842e-02, 9.50522916e-01],
       [2.89748540e-03, 9.97102515e-01],
       [9.919581

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[76, 11],
       [16, 81]])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.87      0.85        87
           1       0.88      0.84      0.86        97

    accuracy                           0.85       184
   macro avg       0.85      0.85      0.85       184
weighted avg       0.85      0.85      0.85       184

